#!/bin/sh

#  preinstall.sh
#  Driver CH341
#
#  Created by Jeroen Arnoldus on 02-12-14.
#  Copyright (c) 2014 Repleo, Amstelveen, The Netherlands - All rights reserved.


cd /Systen/Library/Extensions
if [ -d "usb.kext" ]; then
    kextunload usb.kext
    rm -rf usb.kext
fi

cd /Library/Extensions
if [ -d "osx-ch341.kext" ]; then
    kextunload osx-ch341.kext
    rm -rf osx-ch341.kext
fi
