#!/bin/sh
if [ "$1" = "uninstall" ] ; then
    osascript -e "do shell script \"rm -rf /Applications/Arduino.app\" with administrator privileges"
else
    tar xzfv ~/Downloads/arduino-1.8.9-macosx.zip -C /Applications
fi