#!/bin/sh
if [ "$1" = "uninstall" ] ; then
    rm -rf "/usr/local/share/gcc-arm-none-eabi-7-2018-q2-update"
else
    if [ ! -f "/usr/local/share/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-gcc" ]; then
        tar xzfv ~/Downloads/gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2 -C /usr/local/share
    fi
fi