#!/bin/sh
if [ "$1" = "uninstall" ] ; then
    rm -rf "/usr/local/etc/gcc_arm/avr"
else
    if [ ! -f "/usr/local/etc/gcc_arm/avr/bin/avr-gcc" ]; then
        mkdir /usr/local/etc/gcc_arm
        hdiutil attach ~/Downloads/CrossPack-AVR-20131216.dmg
        pkgutil --expand /Volumes/CrossPack-AVR/CrossPack-AVR.pkg /usr/local/etc/gcc_arm/avr/
        cd /usr/local/etc/gcc_arm/avr/
        mv CrossPack-AVR-flat.pkg/Payload ./
        cat Payload | gzip -d | cpio -id
        rm -r CrossPack-AVR-flat.pkg
        rm -r Resources
        rm Payload
        rm Distribution
        mv ./usr/local/CrossPack-AVR-20131216/* ./
        hdiutil detach /Volumes/CrossPack-AVR
    else
        export PATH="$PATH:/usr/local/etc/gcc_arm/avr/bin/"
        
        #Read
        #avrdude -c ponyser -p attiny13 -P /dev/cu.usbserial  -U flash:r:flash.bin:r

        #Debug
        #avrdude -c ponyser -p attiny13 -P /dev/cu.usbserial -tuF
        #avrdude> sck 1000
        #avrdude: Setting SCK period to 250 usec
        #avrdude> e
        #avrdude: erasing chip
        #avrdude> sck 10
        #avrdude: Setting SCK period to 10 usec
        #avrdude> quit

        #Fuse - Default
        #avrdude -c ponyser -p attiny13 -P /dev/cu.usbserial -U lfuse:w:0x6A:m -U hfuse:w:0xFF:m -B 250
        
        #Fuse - Lock
        #avrdude -c ponyser -p attiny13 -P /dev/cu.usbserial -U lfuse:w:0x7A:m -U hfuse:w:0xFF:m -U lock:w:0xFF:m
        
        #Write
        #avrdude -c USBasp -p attiny13 -P /dev/cu.usbserial -U flash:w:volt-pwm-attiny13.hex:i -B 1024 -b 19200
        avrdude -C /usr/local/etc/gcc_arm/avr/etc/avrdude.conf -c $2 -p attiny13 -P $3 -U flash:w:$1 -F
    fi
fi