#!/bin/sh
if [ "$1" = "uninstall" ] ; then
    rm -rf "/usr/local/share/avr8-gnu-toolchain-darwin_x86_64"
else
    if [ ! -f "/usr/local/share/avr8-gnu-toolchain-darwin_x86_64/bin/avr-gcc" ]; then
        tar xzfv ~/Downloads/avr8-gnu-toolchain-osx-3.6.2.503-darwin.any.x86_64.tar.gz -C /usr/local/share
    fi
fi