#!/bin/sh
if [ "$1" = "uninstall" ] ; then
    rm -rf /Applications/cantact;
else
    if [ ! -d /Applications/cantact ]; then
        tar xzfv ~/Downloads/cantact-v0.3.0-alpha.zip -C /Applications
    else
        /Applications/cantact/bin/cantact
    fi
fi