#!/bin/sh
if [ "$1" = "uninstall" ] ; then
    osascript -e "do shell script \"rm -rf /Applications/cantact;\" with administrator privileges"
else
	tar xzfv ~/Downloads/cantact-v0.3.0-alpha.zip -C /Applications
fi