#!/bin/sh
#sw_vers -buildVersion
#sudo nvram boot-args="kext-dev-mode=1“

cd "$(dirname "$0")"

verlte() {
    [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
}

verlt() {
    [ "$1" = "$2" ] && return 1 || verlte $1 $2
}

installDrivers()
{
    osascript -e "do shell script \"
    for dir in ./kext/*/
    do
        echo $dir
        kext=${dir%*/}
        kext=${kext##*/}

        kextunload /Library/Extensions/$kext
        cp -R ./kext/$kext /Library/Extensions/
        chmod -R 755 /Library/Extensions/$kext
        chown -R root:wheel /Library/Extensions/$kext
        kextload /Library/Extensions/$kext
    done
    \" with administrator privileges"
}

checkDrivers()
{
    #mac-usb-serial Drivers
    for dir in `ls /Library/Extensions/`; do
        if [[ $dir == *osx-* ]] ; then
            echo $dir
            return
        fi
    done

    #Free Drivers
    for dir in `ls ./kext`; do
        #echo $dir
        crc1=$(md5 -q ./kext/$dir/Contents/MacOS/${dir%.*})
        ver1=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "./kext/$dir/Contents/Info.plist")
        echo $crc1
        echo $ver1
        if [ ! -d "/Library/Extensions/$dir" ]; then
            echo "Install ..."
            installDrivers
            return
        else
            crc2=$(md5 -q /Library/Extensions/$dir/Contents/MacOS/${dir%.*})
            ver2=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "/Library/Extensions/$dir/Contents/Info.plist")
            #verlt $ver2 $ver1 && echo "yes" || echo "no"
            if [ "$crc1" != "$crc2" ]; then
                verlt $ver2 $ver1 && installDrivers
                return
            fi
        fi
    done
}

if [ "$1" = "uninstall" ] ; then
    osascript -e "do shell script \"
    for dir in ./kext/*/
    do
        echo $dir
        kext=${dir%*/}
        kext=${kext##*/}
        kextunload /Library/Extensions/$kext
        rm -R /Library/Extensions/$kext
    done
    \" with administrator privileges"
else
    checkDrivers
fi
