#!/bin/sh

cd "$(dirname "$0")"

cp -R ./kext/ProlificUsbSerial.kext /Library/Extensions/
cp -R ./kext/usbserial.kext /Library/Extensions/
cp -R ./kext/SiLabsUSBDriver.kext /Library/Extensions/
cp -R ./kext/FTDIUSBSerialDriver.kext /Library/Extensions/
#sudo kextload -b com.FTDI.driver.FTDIUSBSerialDriver