#!/bin/sh
#sw_vers -buildVersion

cd "$(dirname "$0")"

for dir in ./kext/*/
do
    kext=${dir%*/}
    kext=${kext##*/}
    echo $kext

    sudo kextunload /Library/Extensions/$kext
    sudo cp -R ./kext/$kext /Library/Extensions/
    sudo chmod -R 755 /Library/Extensions/$kext
    sudo chown -R root:wheel /Library/Extensions/$kext
    sudo kextload /Library/Extensions/$kext
done