#!/bin/sh
cd "$(dirname "$0")"
osascript -e "do shell script \"cp -R ./DesignSparkPCB.app /Applications; installer -pkg ~/Downloads/Autodesk_EAGLE_8.1.1_English_Mac_64bit.pkg -target /\" with administrator privileges"
