#!/bin/sh
if [ "$1" = "uninstall" ] ; then
    osascript -e "do shell script \"rm -rf /Applications/Inkscape.app\" with administrator privileges"
else
    cd "$(dirname "$0")"

    hdiutil attach ~/Downloads/Inkscape-1.0.0.dmg

    x=1
    while [ $x -le 20 ]
    do
        if [ -d /Applications/Inkscape.app ]; then
            rsync -avh ./Web/encoder/* ~/Library/Application Support/Inkscape/config/inkscape/
            exit
        fi
        x=$(( $x + 1 ))
        sleep 2
    done
    #hdiutil detach /dev/disk2
fi