#!/bin/sh

#curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6

#curl -O http://pear.php.net/go-pear.phar
#sudo php -d detect_unicode=0 go-pear.phar

#sudo pecl install channel://pecl.php.net/dio-0.0.7 redis swift/swift


cd "$(dirname "$0")"

if [ -f /usr/bin/php ]; then
    if [ ! -f /usr/local/lib/php/extensions/dio.so ]; then
        ditto ./dio/dio.so /usr/local/lib/php/extensions/dio.so
    else
        checksum=`md5 -q /usr/local/lib/php/extensions/dio.so`
        if [ $checksum  != "a1b979cf3fdcb1e00083b78d9c9c68ae" ]; then
            ditto ./dio/dio.so /usr/local/lib/php/extensions/dio.so
        fi
    fi
    if ! grep -lr "extension=dio.so" /usr/local/etc/php.ini ; then
        cp /etc/php.ini /usr/local/etc/php.ini
        chmod 644 /usr/local/etc/php.ini
        echo "extension_dir=/usr/local/lib/php/extensions/" >> /usr/local/etc/php.ini
        echo "extension=dio.so" >> /usr/local/etc/php.ini
    fi
fi

./driver
