#!/bin/sh

xcode-select --install
#open /Applications/XCode.app

# NOTE: You should also add this line to ~/.bashrc or ~/.bash_profile (in your home directory)
# so you don't have to remember to do this every time you want to compile firmware.
export PATH="$PATH:/usr/local/gcc_arm/gcc-arm-none-eabi-5_3-2016q1/bin/"

cd ~/Documents/firmware/

#--------- SOURCECODE ------------

if [ ! -d src ]; then
    git clone -b sync_motor https://github.com/tumanako/tumanako-inverter-fw-motorControl.git
    ditto ./tumanako-inverter-fw-motorControl/src/sine ./src
fi

#--------- LIBOPENCM3 ------------

if [ ! -d libopencm3 ]; then
    git clone https://github.com/libopencm3/libopencm3.git
    cd libopencm3
    make
    #cp examples/stm32/f1/Makefile.include ~/Documents/firmware/src/
    #cp examples/stm32/f1/stm32-h103/stm32-h103.ld ~/Documents/firmware/src/
fi

#--------- BOOTLOADER ------------

cd ~/Documents/bootloader/

if [ ! -f /usr/local/gcc_arm/gcc-arm-none-eabi-5_3-2016q1/arm-none-eabi/lib/libopencm3_stm32f1.a ]; then
    cp -r ../firmware/libopencm3/lib /usr/local/gcc_arm/gcc-arm-none-eabi-5_3-2016q1/arm-none-eabi
fi
arm-none-eabi-gcc -I../firmware/libopencm3/include -c stm32_loader.c -o stm32_loader.o
arm-none-eabi-gcc -L../firmware/libopencm3/lib -Tstm32_loader.ld -nostartfiles -Wl,--gc-sections,-Map,linker.map -o stm32_loader stm32_loader.o -lopencm3_stm32f1
arm-none-eabi-objcopy -Obinary stm32_loader ../firmware/stm32_loader.bin
arm-none-eabi-objcopy -Oihex stm32_loader ../firmware/stm32_loader.hex

#--------- FIRMWARE --------------

cd ~/Documents/firmware/src/
if [ ! -d include ]; then
    mkdir include
    cp -r ../libopencm3/include/libopencm3 ./include
fi
make clean
make
#---------------------------------

open ~/Documents/firmware
