#!/bin/sh
if [ "$1" = "uninstall" ]; then
    rm -rf "/usr/local/share/gnu-mcu-eclipse"
else
    if [ ! -f "/usr/local/share/gnu-mcu-eclipse/openocd/0.10.0-10-20181020-0522/bin/openocd" ]; then
        tar xzfv ~/Downloads/gnu-mcu-eclipse-openocd-0.10.0-10-20181020-0522-macos.tgz -C /usr/local/share
    else
        export PATH="$PATH:/usr/local/share/gnu-mcu-eclipse/openocd/0.10.0-10-20181020-0522/bin/"
        cd /usr/local/share/gnu-mcu-eclipse/openocd/0.10.0-10-20181020-0522/scripts/
        
        #halt
        #flash erase_sector 0 0 last
        #dump_image dump.bin 0x0 0x00020000
        
        #The main firmware must be linked to start at address 0x08001000
        #The bootloader starts at address 0x08000000 and can be 4k in size

        case "$1" in
          *".hex"*) ADDRESS="" ;;
          *".HEX"*) ADDRESS="" ;;
          *)        ADDRESS=" 0x08000000" ;;
        esac

        if [ "$3" = "ram" ]; then
            ADDRESS=" 0x08001000"
        fi

        openocd -f ./$2 -f ./board/olimex_stm32_h103.cfg  -c "init" -c "reset halt" -c "flash write_image erase unlock \"$1\"$ADDRESS" -c "reset" -c "shutdown" 
    fi
fi