#!/bin/sh
if [ "$1" = "uninstall" ] ; then
    rm -rf "/usr/local/etc/gcc_arm/openocd"
else
    if [ ! -f "/usr/local/etc/gcc_arm/openocd/bin/openocd" ]; then
        mkdir /usr/local/etc/gcc_arm
        pkgutil --expand ~/Downloads/gnuarmeclipse-openocd-osx-0.10.0-201601101000-dev.pkg /usr/local/etc/gcc_arm/openocd/
        cd /usr/local/etc/gcc_arm/openocd/
        cat Payload | gzip -d | cpio -id
        rm Bom
        rm PackageInfo
        rm Payload
    else
        export PATH="$PATH:/usr/local/etc/gcc_arm/openocd/bin/"
        cd /usr/local/etc/gcc_arm/openocd/scripts/
        
        #halt
        #flash erase_sector 0 0 last
        #dump_image dump.bin 0x0 0x00020000
        
        #The main firmware must be linked to start at address 0x08001000
        #The bootloader starts at address 0x08000000 and can be 4k in size

        openocd -f ./$2 -f ./board/olimex_stm32_h103.cfg  -c "init" -c "reset halt" -c "flash write_image erase $1 0x08000000" -c "reset" -c "shutdown" 
    fi
fi