#!/bin/sh

xPacksPath="/usr/local/share/xPacks/openocd/0.10.0-13"

if [ "$1" = "uninstall" ]; then
    rm -rf "$xPacksPath"
else
    if [ ! -f "$xPacksPath/bin/openocd" ]; then
        #MacOS 10.15
        if [ ! -d "/usr/local/share" ]; then
            osascript -e "do shell script \"mkdir /usr/local/share; chown -R $(whoami) /usr/local/share\" with administrator privileges"
        fi
        tar xzfv ~/Downloads/xpack-openocd-0.10.0-13-darwin-x64.tgz -C /usr/local/share
        case ":$PATH:" in
          *:$xPacksPath/bin:*) echo $PATH;;
          *) echo "export PATH=\${PATH}:$xPacksPath/bin" >> ~/.zprofile;;
        esac
        source ~/.zprofile
    else
        export PATH="$PATH:$xPacksPath/bin/"
        cd $xPacksPath/scripts/
        
        #halt
        #flash erase_sector 0 0 last
        #dump_image dump.bin 0x0 0x00020000
        
        #The main firmware must be linked to start at address 0x08001000
        #The bootloader starts at address 0x08000000 and can be 4k in size

        case "$1" in
          *".hex"*) ADDRESS="" ;;
          *".HEX"*) ADDRESS="" ;;
          *)        ADDRESS=" 0x08000000" ;;
        esac

        if [ "$3" = "ram" ]; then
            ADDRESS=" 0x08001000"
        fi

        openocd -f ./$2 -f ./board/olimex_stm32_h103.cfg  -c "init" -c "reset halt" -c "flash write_image erase unlock \"$1\"$ADDRESS" -c "reset" -c "shutdown" 
    fi
fi