#!/bin/sh

cd "$(dirname "$0")"

if [ -f /usr/bin/php ]; then
    if grep -q "extension_dir=$(dirname "$0")/dio" "/usr/local/etc/php.ini"; then
        echo "ok"
    else
        cp -R /etc/php.ini /usr/local/etc/php.ini
        #cp -R ./dio/php.ini /usr/local/etc/php.ini
        chmod 644 /usr/local/etc/php.ini
        echo "extension_dir=$(dirname "$0")/dio/" >> /usr/local/etc/php.ini
        echo "extension=dio.so" >> /usr/local/etc/php.ini
    fi

    #curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6
    #curl -O http://pear.php.net/go-pear.phar
    #sudo php -d detect_unicode=0 go-pear.phar
    #sudo pecl install channel://pecl.php.net/dio-0.0.7 redis swift/swift
fi
