#!/bin/sh

browser="Safari"

myIP=$(ifconfig | grep "inet " | grep -v "127.0.0.1" | cut -f2 -d' '| awk 'NR==1{print $1}')

if [ -z "$myIP" ]; then
    myIP="127.0.0.1"
fi

checkUSB()
{
    shopt -s nocasematch
    for ((i = 0 ; i < 30 ; i++ )); do
        for serial in $(ls /dev/cu.*); do
            if [[ $serial == *"usb"* ]]; then
                if grep -q $serial "$(dirname "$0")/Web/config.inc.php"; then
                    i=30
                else
                    cp -R "$(dirname "$0")/Web/config.inc" "$(dirname "$0")/Web/config.inc.php"
                    sed -i '' 's~/dev/cu.usbserial~'"$serial"'~g' "$(dirname "$0")/Web/config.inc.php"
                fi
                open -a $browser http://$myIP:8080 &
                return
            fi
        done
        echo "... Waiting for RS232-USB"
        if [[ $i -eq 1 ]]; then
            open -a $browser http://$myIP:8080/connect.html &
        fi
        sleep 2
    done
}

checkDrivers()
{
    open -a $browser http://$myIP:8080/drivers.html &
    echo "============================"
    echo "Installing RS232-USB Drivers"
    echo "============================"
    osascript -e "do shell script \"./driver\" with administrator privileges"
}

cd "$(dirname "$0")"

if [ -d /Applications/Firefox.app ]; then
    browser="Firefox"
else if[ -d /Applications/Chrome.app ]
    browser="Chrome"
fi

pkill -9 php
/usr/bin/php -S 0.0.0.0:8080 -t "$(dirname "$0")/Web/" &
sleep 2

for dir in `ls ./kext`; do
    if [ ! -d "/Library/Extensions/$dir" ]; then
        checkDrivers
    fi
done

checkUSB