#!/bin/sh

myIP=$(ifconfig | grep "inet " | grep -v "127.0.0.1" | cut -f2 -d' '| awk 'NR==1{print $1}')

if [ -z "$myIP" ]; then
    myIP="127.0.0.1"
fi

checkUSB()
{
    shopt -s nocasematch
    for ((i = 0 ; i < 30 ; i++ )); do
        for serial in $(ls /dev/cu.*); do
            if [[ $serial == *usb* ]] || [[ $serial == *ch34* ]] || [[ $serial == *pl23* ]] ; then
echo "{
    \"serial\": {
        \"port\": \"$serial\",
        \"web\": 8081,
		\"timeout\": 12
    }
}" > "$(dirname "$0")/Web/js/serial.json"

                i=30
                open -a $browser http://$myIP:8080 &
                return
            fi
        done
        echo "... Waiting for RS232-USB"
        if [[ $i -eq 1 ]]; then
            open -a $browser http://$myIP:8080/connect.html &
        fi
        sleep 2
    done
}

checkDrivers()
{
    open -a $browser http://$myIP:8080/drivers.html &
    echo "============================"
    echo "Installing RS232-USB Drivers"
    echo "============================"
    osascript -e "do shell script \"./driver\" with administrator privileges"
}

cd "$(dirname "$0")"

if [ -d /Applications/Firefox.app ]; then
    browser="Firefox"
elif [ -d /Applications/Chrome.app ]; then
    browser="Chrome"
else
    browser="Safari"
fi

pkill -9 php
/usr/bin/php -S 0.0.0.0:8080 -t "$(dirname "$0")/Web/" &
/usr/bin/php -S 0.0.0.0:8081 -t "$(dirname "$0")/Web/" &
sleep 2

for dir in `ls ./kext`; do
    if [ ! -d "/Library/Extensions/$dir" ]; then
        checkDrivers
    fi
done

checkUSB