#!/bin/sh

if [ "$1" = "uninstall" ] ; then
    rm -rf ~/Documents/stm32-sine-master
else
    
    if [ ! -d ~/Documents/stm32-sine-master ]; then
        tar xzfv ~/Downloads/stm32-sine-master.zip -C ~/Documents/
    else
    
        if [ ! -f /usr/bin/gcc ]; then
            xcode-select --install
            #open /Applications/XCode.app
        fi

        GCC_ARM="/usr/local/share/gcc-arm-none-eabi-8-2018-q4-major"
        export PATH="$PATH:$GCC_ARM/bin/"
        
        #--------- LIBOPENCM3 ------------
        cd ~/Documents/stm32-sine-master/
        if [ -z libopencm3 ]; then
            git clone https://github.com/jsphuebner/libopencm3.git --quiet
            #git clone https://github.com/libopencm3/libopencm3.git --quiet
        fi
        cd libopencm3
        if [ ! -f lib/libopencm3_stm32f1.a ]; then

            make clean
            make TARGETS=stm32/f1
            
            #Overwrite existing with new version
            ditto lib "$GCC_ARM/arm-none-eabi/lib"
            ditto include "$GCC_ARM/arm-none-eabi/include"
            #A Fix
            cp "$GCC_ARM/arm-none-eabi/lib/cortex-m-generic.ld" "$GCC_ARM/arm-none-eabi/lib/libopencm3_stm32f1.ld"
        fi
        #--------- LIBOPENINV ------------
        cd ~/Documents/stm32-sine-master/
        if [ -z libopeninv ]; then
            git clone https://github.com/jsphuebner/libopeninv.git --quiet
        fi
        #--------- BOOTLOADER ------------
        cd ~/Documents/stm32-sine-master/src/
        if [ ! -d bootloader ]; then
            git clone https://github.com/jsphuebner/tumanako-inverter-fw-bootloader.git --quiet
            mv tumanako-inverter-fw-bootloader bootloader
        fi
        cd bootloader
        make clean
        make
        cd bootupdater
        make clean
        make
        #--------- FIRMWARE --------------
        cd ~/Documents/stm32-sine-master
        make clean
        make
        make CONTROL=FOC
        #--------- ATtiny13 --------------
        export PATH="$PATH:/usr/local/share/avr8-gnu-toolchain-darwin_x86_64/bin/"

        cd ~/Documents/stm32-sine-master/
        if [ ! -d attiny13 ]; then
            cp -r "$(dirname "$0")/Web/pcb/Hardware v1.0/firmware/attiny13" ./src/
        fi
        cd ./src/attiny13
        avr-gcc -g -mmcu=attiny13 -Os -Os -o volt-pwm-attiny13.o volt-pwm-attiny13.c -DF_CPU=96000000
        avr-objcopy -R .eeprom -O binary volt-pwm-attiny13.o volt-pwm-attiny13.bin
        avr-objcopy -R .eeprom -O ihex volt-pwm-attiny13.o volt-pwm-attiny13.hex
        mv volt-pwm-attiny13.bin ../
        mv volt-pwm-attiny13.hex ../
        #---------------------------------

        open ~/Documents/stm32-sine-master
    fi
fi