#!/bin/sh
if [ "$1" = "uninstall" ]; then
    rm -rf "/usr/local/share/stlink-1.3.0-macosx-amd64"
else
    if [ ! -f "/usr/local/share/stlink-1.3.0-macosx-amd64/bin/st-flash" ]; then
      #MacOS 10.15
      if [ ! -d "/usr/local/share" ]; then
        osascript -e "do shell script \"mkdir /usr/local/share; chown -R $(whoami) /usr/local/share\" with administrator privileges"
      fi
      tar xzfv ~/Downloads/stlink-1.3.0-macosx-amd64.zip -C /usr/local/share
    else
      export PATH="$PATH:/usr/local/share/stlink-1.3.0-macosx-amd64/bin/"
      cd /usr/local/share/stlink-1.3.0-macosx-amd64/bin/
	
		if [ "$2" = "ram" ]; then
        ADDRESS=" 0x08001000"
      fi
	
      case "$1" in
        *".hex"*) ADDRESS="" ;;
        *".HEX"*) ADDRESS="" ;;
        *)        ADDRESS=" 0x08000000" ;;
      esac

      case "$1" in
        *".hex"*) FORMAT=" --format ihex" ;;
        *".HEX"*) FORMAT=" --format ihex" ;;
        *)        FORMAT="" ;;
      esac
	
      st-flash --reset$FORMAT write "$1"$ADDRESS
    fi
fi