#!/bin/sh
if [ "$1" = "uninstall" ]; then
    rm -rf "/usr/local/share/stlink-1.3.0-macosx-amd64"
else
    if [ ! -f "/usr/local/share/stlink-1.3.0-macosx-amd64/bin/st-flash" ]; then
        tar xzfv ~/Downloads/stlink-1.3.0-macosx-amd64.zip -C /usr/local/share
    else
        cd "$PATH:/usr/local/share/stlink-1.3.0-macosx-amd64/bin/"
	
		if [ "$2" = "ram" ]; then
            ADDRESS=" 0x08001000"
        fi
		
        case "$1" in
          *".hex"*) ADDRESS="" ;;
          *".HEX"*) ADDRESS="" ;;
          *)        ADDRESS=" 0x08000000" ;;
        esac
		
        st-flash --reset write $1$ADDRESS
    fi
fi