#!/bin/sh

hdiutil attach ~/Downloads/XQuartz-2.7.9.dmg
osascript -e "do shell script \"installer -pkg /Volumes/XQuartz-2.7.9/XQuartz.pkg -target /\" with administrator privileges"
hdiutil detach /Volumes/XQuartz-2.7.9