#!/bin/sh

#  postinstall.sh
#  Driver PL2303
#
#  Created by Jeroen Arnoldus on 02-12-14.
#  Copyright (c) 2014 Repleo, Amstelveen, The Netherlands - All rights reserved.

touch /Library/Extensions
cd /Library/Extensions
kextload osx-pl2303.kext | true
