#!/bin/sh

#  preinstall.sh
#  Driver PL341
#
#  Created by Jeroen Arnoldus on 02-12-14.
#  Copyright (c) 2014 Repleo, Amstelveen, The Netherlands - All rights reserved.


cd /Library/Extensions
if [ -d "osx-pl2303.kext" ]; then
    kextunload osx-pl2303.kext
    rm -rf osx-pl2303.kext
fi

cd /Library/Extensions
if [ -d "Driver_PL2303.kext" ]; then
    kextunload Driver_PL2303.kext
    rm -rf Driver_PL2303.kext
fi

cd /System/Library/Extensions
if [ -d "Driver_PL2303.kext" ]; then
    kextunload Driver_PL2303.kext
    rm -rf Driver_PL2303.kext
fi
