#!/bin/sh

cd "$(dirname "$0")"

cp ./uart_linux.patch "$1"
cd "$1/libupdate"
patch -p0 < uart_linux.patch

gcc -std=c99 -O2 -Wall -D_GNU_SOURCE  -c main.c -o main.o
gcc -std=c99 -O2 -Wall -D_GNU_SOURCE  -c uart_linux.c -o uart_linux.o
rm -f lib_update.a
ar -r -s lib_update.a main.o uart_linux.o

cd "$1/updater"
if ! grep -lr "cu.usbserial" main.c; then
    sed -i '' 's/ttyS0/cu.usbserial/' main.c
fi
gcc -Wall -O2 -I../lib_update -I../libupdate -c main.c -o main.o
g++ -o updater main.o  ../libupdate/lib_update.a
