#!/bin/sh

cd "$(dirname "$0")"

hdiutil attach ~/Downloads/Inkscape-0.91-1-x11-10.7-x86_64.dmg

x=1
while [ $x -le 120 ]
do
    if [ -f /Applications/Inkscape.app/Contents/MacOS/Inkscape ]; then
        ditto ./encoder/encoder_disk_generator.py ~/.config/inkscape/extensions/encoder_disk_generator.py
        ditto ./encoder/encoder_disk_generator.inx ~/.config/inkscape/extensions/encoder_disk_generator.inx
        ditto ./encoder/preferences.xml ~/.config/inkscape/preferences.xml
        break
    fi
    x=$(( $x + 1 ))
    sleep 4
done

#hdiutil detach /dev/disk2