#!/bin/sh

cd "$(dirname "$0")"

if [ -f /usr/bin/php ]; then
    if grep -lr "extension=dio.so" /etc/php.ini; then
        sudo cp ./dio/dio.so /usr/lib/php/extensions/dio.so
        sudo cat "extension_dir=/usr/lib/php/extensions/" >> /etc/php.ini
        sudo cat "extension=dio.so" >> /etc/php.ini
    fi
else
    if [ ! -f /usr/local/php5/bin/php ]; then
        curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6
        sudo rm -rf /usr/local/packager/registry.log
        #export PATH=/usr/local/php5/bin:$PATH
    fi

    if [ ! -f /usr/local/php5/lib/php/extensions/no-debug-non-zts-20131226/dio.so ]; then
        #sudo /usr/local/php5/bin/pecl install dio-0.0.7
        sudo cp ./dio/dio.so /usr/local/php5/lib/php/extensions/no-debug-non-zts-20121212/
        sudo cat "extension_dir=/usr/local/php5/lib/php/extensions/no-debug-non-zts-20131226" >> /usr/local/php5/php.d/dio.ini
        sudo cat "extension=dio.so" >> /usr/local/php5/php.d/dio.ini
    fi
fi

if [ ! -d "/Library/Extensions/ProlificUsbSerial.kext" ]; then
    cp -R ./web/driver/ProlificUsbSerial.kext /Library/Extensions/
fi