#!/bin/sh

cd "$(dirname "$0")"

hdiutil attach ~/Downloads/XQuartz-2.7.9.dmg

x=1
while [ $x -le 120 ]
do
    if [ -f /Applications/Utilities/XQuartz.app/Contents/MacOS/X11 ]; then
        break
    fi
    x=$(( $x + 1 ))
    sleep 4
done

#hdiutil detach /dev/disk2