#!/bin/sh

# System Updates
sudo apt-get update
sudo apt-get upgrade

# Install Web-Browser
sudo apt-get install xutils -y
sudo apt-get install epiphany-browser -y

# Install WebServer (/var/www/html/)
sudo apt-get install apache2 -y
sudo apt-get install php5 libapache2-mod-php5 -y
sudo usermod -a -G dialout www-data

# Web-Browser Auto-Start
sudo cp ./run /home/pi/
sudo chmod 755 /home/pi/run
if grep -q "./home/pi/run" /etc/rc.local; then
    echo "Startup OK"
else
    sudo echo "sudo xinit ./home/pi/run &" >> /etc/rc.local
fi

# Install CAN Interface
sudo apt-get install can-utils
if grep -q "mcp2515-can0" /boot/config.txt; then
    echo "SPI OK"
else
    sudo cp -p /boot/config.txt /boot/config.txt.bak
    sudo echo "dtparam=spi=on" >> /boot/config.txt
    sudo echo "dtoverlay=mcp2515-can0,oscillator=8000000,interrupt=12" >> /boot/config.txt
    sudo echo "dtoverlay=spi-bcm2835-overlay" >> /boot/config.txt
fi
if grep -q "auto can0" /etc/network/interface; then
    echo "CAN OK"
else
    #sudo ip link set can0 up type can bitrate 125000
    sudo echo "auto can0" >> /etc/network/interface
    sudo echo "iface can0 can static bitrate 125000" >> /etc/network/interface
fi
#cansend can0 456#43414e2054657374

# Set Boot Option to B4 (Desktop Autoboot)
sudo raspi-config