#!/bin/sh

if [ ! -d "/Applications/Wine Staging.app" ]; then
    cd ~/Downloads
    echo "Downloading Wine 4.12 for Mac ..."
    curl -k -L -O -C - https://dl.winehq.org/wine-builds/macosx/pool/winehq-staging-4.12.1.pkg
    osascript -e "do shell script \"installer -pkg ~/Downloads/winehq-staging-4.12.1.pkg -target /\" with administrator privileges"
fi
export DISPLAY=:0.0
export PATH=$PATH:/Applications/Wine\ Staging.app/Contents/Resources/wine/bin/
export LANG="en_US"
export WINEARCH=win32
export WINEPREFIX="$HOME/.wine"
export DYLD_FALLBACK_LIBRARY_PATH=/usr/X11/lib
export FREETYPE_PROPERTIES="truetype:interpreter-version=35"

if [ ! -d "$HOME/.wine/drive_c/Program Files/DesignSpark/DesignSpark PCB 8.1" ]; then

    export PATH=$PATH:"$(dirname "$0")"

    winetricks --self-update

    winetricks fontsmooth-rgb
    winetricks settings fontsmooth=rgb

    #winetricks d3dx9
    winetricks d3dx10

    #winetricks mfc40
    winetricks mfc42

    #winetricks wine-mono
    #winetricks dotnet46

    #winetricks vcrun6
    winetricks vcrun2010

    #mkdir "$HOME/.wine/drive_c/DSLib"

    if [ ! -f "$HOME/Downloads/DesignSparkPCB_v8.1.2.exe" ]; then
        cd ~/Downloads
        echo "Downloading DesignSparkPCB ..."
        curl -k -L -O -C - https://pcb.designspark.info/DesignSparkPCB_v8.1.2.exe
    fi

    cd "/Applications/Wine Staging.app/Contents/Resources/wine/bin/"
    ./wine ~/Downloads/DesignSparkPCB_v8.1.2.exe
fi
open -a "Wine Staging" --args "$HOME/.wine/drive_c/Program Files/DesignSpark/DesignSpark PCB 8.1/DesignSpark.exe" "$1"